name: shop_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  ionicons: ^0.2.2
  google_fonts: ^5.1.0
  iconsax: ^0.0.8
  http: ^1.2.2  # Updated HTTP package version
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.2.2
  location: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter:

  uses-material-design: true

  assets:
    - assets/
    - google_fonts/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ReadersHub.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/ReadersHub.png"
